version: '3'

services:

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

  web:
    build: .
    ports:
      - "8081:80"
    depends_on:
      - db
    volumes:
      - ./public/:/var/www/html/
    stdin_open: true
    tty: true
